com.ucoruh.password.Password Class Reference
Represents a stored password entry for a specific service.
Public Member Functions
Password (String service, String username, String password)
Constructs a Password object with service, username, and password.
String getService ()
Returns the service name.
String getUsername ()
Returns the username.
String getPassword ()
Returns the password string.
void setUsername (String username)
Sets a new username for this password entry.
void setPassword (String password)
Sets a new password for this password entry.
String toString ()
Returns a string representation of the Password object.
Detailed Description
Represents a stored password entry for a specific service.
This class provides a structure to store and manage credentials such as service name, username, and password. You can retrieve or update these fields through the provided getter and setter methods.
Definition at line 12 of file Password.java.
Constructor & Destructor Documentation
Password()
com.ucoruh.password.Password.Password (String service, String username, String password)
Constructs a Password object with service, username, and password.
Parameters
service the service name (e.g., Gmail, Facebook)
username the associated username
password the password string
Definition at line 35 of file Password.java.
                                                                      {
        this.service = service;
        this.username = username;
        this.password = password;
    }
Member Function Documentation
getPassword()
String com.ucoruh.password.Password.getPassword ()
Returns the password string.
Returns
the password string associated with this password entry.
Definition at line 64 of file Password.java.
                                {
        return password;
    }
Referenced by com.ucoruh.password.FilePasswordStorage.add().
getService()
String com.ucoruh.password.Password.getService ()
Returns the service name.
Returns
the service name associated with this password entry.
Definition at line 46 of file Password.java.
                               {
        return service;
    }
Referenced by com.ucoruh.password.FilePasswordStorage.add().
getUsername()
String com.ucoruh.password.Password.getUsername ()
Returns the username.
Returns
the username associated with this password entry.
Definition at line 55 of file Password.java.
                                {
        return username;
    }
Referenced by com.ucoruh.password.FilePasswordStorage.add().
setPassword()
void com.ucoruh.password.Password.setPassword (String password)
Sets a new password for this password entry.
Parameters
password the new password string to be set for this password entry.
Definition at line 82 of file Password.java.
                                             {
        this.password = password;
    }
setUsername()
void com.ucoruh.password.Password.setUsername (String username)
Sets a new username for this password entry.
Parameters
username the new username to be set for this password entry.
Definition at line 73 of file Password.java.
                                             {
        this.username = username;
    }
toString()
String com.ucoruh.password.Password.toString ()
Returns a string representation of the Password object.
Returns
a string with service, username, and password details.
Definition at line 92 of file Password.java.
                             {
        return "Service: " + service + " | Username: " + username + " | Password: " + password;
    }
The documentation for this class was generated from the following file:
password-app/src/main/java/com/ucoruh/password/Password.java