com.ucoruh.password.PasswordApp Class Reference
Entry point for the Password Manager console application.
Static Public Member Functions
static void runApp (Scanner scanner, PrintStream out)
Runs the application using the provided Scanner and PrintStream.
static void main (String[] args)
Main method to launch the console application.
Detailed Description
Entry point for the Password Manager console application.
This class provides the main method for launching the application and a runApp method which handles the overall flow of the application including authentication and menu operations.
Definition at line 12 of file PasswordApp.java.
Member Function Documentation
main()
static void com.ucoruh.password.PasswordApp.main (String[] args) [static]
Main method to launch the console application.
This method serves as the entry point to the application and initiates the runApp method.
Parameters
args Command-line arguments (not used).
Definition at line 127 of file PasswordApp.java.
                                           {
        // Check whether to start in GUI mode
        boolean useGUI = true;
        
        for (String arg : args) {
            if (arg.equalsIgnoreCase("--console") || arg.equalsIgnoreCase("-c")) {
                useGUI = false;
                break;
            }
        }
        
        if (useGUI) {
            // Start in GUI mode
            try {
                // Set system look and feel
                javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
                
                // Font settings
                java.awt.Font defaultFont = new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14);
                javax.swing.UIManager.put("Button.font", defaultFont);
                javax.swing.UIManager.put("Label.font", defaultFont);
                javax.swing.UIManager.put("TextField.font", defaultFont);
                javax.swing.UIManager.put("PasswordField.font", defaultFont);
                javax.swing.UIManager.put("TextArea.font", defaultFont);
                javax.swing.UIManager.put("ComboBox.font", defaultFont);
                javax.swing.UIManager.put("CheckBox.font", defaultFont);
                javax.swing.UIManager.put("RadioButton.font", defaultFont);
            } catch (Exception e) {
                e.printStackTrace();
            }
            
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    try {
                        com.ucoruh.password.gui.PasswordManagerGUI frame = new com.ucoruh.password.gui.PasswordManagerGUI();
                        frame.setVisible(true);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            });
        } else {
            // Start in console mode
            Scanner scanner = new Scanner(System.in);
            runApp(scanner, System.out);
            scanner.close();
        }
    }
References com.ucoruh.password.gui.PasswordManagerGUI.PasswordManagerGUI(), and com.ucoruh.password.PasswordApp.runApp().
runApp()
static void com.ucoruh.password.PasswordApp.runApp (Scanner scanner, PrintStream out) [static]
Runs the application using the provided Scanner and PrintStream.
This method initializes user authentication and starts the main menu loop for handling various operations like user authentication, secure storage of passwords, password generation, auto-login feature, and platform management.
Parameters
scanner The Scanner object for user input.
out The PrintStream object for output.
Definition at line 23 of file PasswordApp.java.
                                                                {
        AuthManager auth = AuthManager.getInstance();
        if (!auth.isMasterPasswordSet()) {
            out.print("Set master password: ");
            auth.createMasterPassword(scanner);
        }
        out.print("Enter master password to login: ");
        if (auth.login(scanner)) {
            PasswordManager pm = new PasswordManager(auth.getMasterPassword());
            int choice = -1;
            do {
                out.println("\n==== MAIN MENU ====");
                out.println("1. User Authentication");
                out.println("2. Secure Storage of Passwords");
                out.println("3. Password Generator");
                out.println("4. Auto-Login Feature");
                out.println("5. Multi-Platform Compatibility");
                out.println("0. Exit");
                out.print("Your choice: ");
                String input = scanner.nextLine();
                try {
                    choice = Integer.parseInt(input);
                } catch (NumberFormatException e) {
                    out.println("Invalid number.");
                    continue;
                }
                switch (choice) {
                    case 1:
                        auth.userMenu(scanner);
                        break;
                    case 2:
                        pm.menu(scanner, out);
                        break;
                    case 3:
                        passwordGeneratorMenu(scanner, out);
                        break;
                    case 4:
                        AutoLoginManager.menu(scanner, pm);
                        break;
                    case 5:
                        platformMenu(scanner, out);
                        break;
                    case 0:
                        out.println("Exiting...");
                        break;
                    default:
                        out.println("Invalid choice.");
                        break;
                }
            } while (choice != 0);
        } else {
            out.println("Login failed.");
        }
    }
References com.ucoruh.password.AuthManager.createMasterPassword(), com.ucoruh.password.AuthManager.getInstance(), com.ucoruh.password.AuthManager.getMasterPassword(), com.ucoruh.password.AuthManager.isMasterPasswordSet(), com.ucoruh.password.AuthManager.login(), com.ucoruh.password.AutoLoginManager.menu(), com.ucoruh.password.PasswordManager.menu(), and com.ucoruh.password.AuthManager.userMenu().
Referenced by com.ucoruh.password.PasswordApp.main().
The documentation for this class was generated from the following file:
password-app/src/main/java/com/ucoruh/password/PasswordApp.java