com.ucoruh.password.PasswordGenerator Class Reference
Utility class for generating random passwords.
Static Public Member Functions
static String generatePassword (int length)
Generates a random password of a given length.
static String generatePassword (int length, boolean includeUppercase, boolean includeLowercase, boolean includeDigits, boolean includeSpecial)
Generates a random password with specific character sets.
static void generate (Scanner scanner)
Prompts user for password length and generates a password.
Detailed Description
Utility class for generating random passwords.
This class provides methods to generate secure random passwords using configurable character sets.
Definition at line 13 of file PasswordGenerator.java.
Member Function Documentation
generate()
static void com.ucoruh.password.PasswordGenerator.generate (Scanner scanner) [static]
Prompts user for password length and generates a password.
This method reads the desired password length from the user input using the provided Scanner, then generates and prints the random password.
Parameters
scanner Scanner object for reading user input
Definition at line 133 of file PasswordGenerator.java.
                                                 {
        System.out.print("Enter desired password length: ");
        try {
            int length = Integer.parseInt(scanner.nextLine());
            String newPassword = generatePassword(length);
            System.out.println("Generated Password: " + newPassword);
        } catch (NumberFormatException e) {
            System.out.println("Invalid input. Please enter a valid number.");
        }
    }
References com.ucoruh.password.PasswordGenerator.generatePassword().
generatePassword() [1/2]
static String com.ucoruh.password.PasswordGenerator.generatePassword (int length) [static]
Generates a random password of a given length.
This method uses a random number generator and a predefined character set to create a password string of the specified length. If a negative length is provided, an empty string is returned.
Parameters
length The desired length of the password
Returns
String A randomly generated password
Definition at line 54 of file PasswordGenerator.java.
                                                      {
        // For backward compatibility, use all character sets
        return generatePassword(length, true, true, true, true);
    }
References com.ucoruh.password.PasswordGenerator.generatePassword().
Referenced by com.ucoruh.password.PasswordGenerator.generate(), and com.ucoruh.password.PasswordGenerator.generatePassword().
generatePassword() [2/2]
static String com.ucoruh.password.PasswordGenerator.generatePassword (int length, boolean includeUppercase, boolean includeLowercase, boolean includeDigits, boolean includeSpecial) [static]
Generates a random password with specific character sets.
This method allows selective inclusion of character sets (uppercase letters, lowercase letters, digits, and special characters) in the generated password. At least one character set must be included.
Parameters
length The desired length of the password
includeUppercase Whether to include uppercase letters (A-Z)
includeLowercase Whether to include lowercase letters (a-z)
includeDigits Whether to include digits (0-9)
includeSpecial Whether to include special characters
Returns
String A randomly generated password meeting the specified criteria
Definition at line 72 of file PasswordGenerator.java.
                                                                 {
        // Return empty string for zero or negative length
        if (length <= 0) {
            return "";
        }
        
        // Build the character set based on includes
        StringBuilder charSetBuilder = new StringBuilder();
        if (includeUppercase) charSetBuilder.append(UPPERCASE_CHARS);
        if (includeLowercase) charSetBuilder.append(LOWERCASE_CHARS);
        if (includeDigits) charSetBuilder.append(DIGIT_CHARS);
        if (includeSpecial) charSetBuilder.append(SPECIAL_CHARS);
        
        // If no character set is selected, use lowercase as default
        String charSet = charSetBuilder.length() > 0 ? charSetBuilder.toString() : LOWERCASE_CHARS;
        
        // Generate the password
        StringBuilder password = new StringBuilder(length);
        Random random = new Random();
        
        // Ensure at least one character from each selected char set
        if (length >= 1 && includeUppercase && password.length() < length) {
            password.append(UPPERCASE_CHARS.charAt(random.nextInt(UPPERCASE_CHARS.length())));
        }
        if (length >= 2 && includeLowercase && password.length() < length) {
            password.append(LOWERCASE_CHARS.charAt(random.nextInt(LOWERCASE_CHARS.length())));
        }
        if (length >= 3 && includeDigits && password.length() < length) {
            password.append(DIGIT_CHARS.charAt(random.nextInt(DIGIT_CHARS.length())));
        }
        if (length >= 4 && includeSpecial && password.length() < length) {
            password.append(SPECIAL_CHARS.charAt(random.nextInt(SPECIAL_CHARS.length())));
        }
        
        // Fill the rest with random characters from the selected set
        while (password.length() < length) {
            int index = random.nextInt(charSet.length());
            password.append(charSet.charAt(index));
        }
        
        // Shuffle the characters to avoid predictable patterns
        char[] passChars = password.toString().toCharArray();
        for (int i = passChars.length - 1; i > 0; i--) {
            int j = random.nextInt(i + 1);
            char temp = passChars[i];
            passChars[i] = passChars[j];
            passChars[j] = temp;
        }
        
        return new String(passChars);
    }
The documentation for this class was generated from the following file:
password-app/src/main/java/com/ucoruh/password/PasswordGenerator.java