com.ucoruh.password.DatabasePasswordStorage Class Reference
SQLite-based implementation of password storage.
Public Member Functions
DatabasePasswordStorage (String masterPassword)
Constructs a DatabasePasswordStorage object and initializes the database.
void add (Scanner scanner)
Adds a new password entry to the database using user input.
void view ()
Retrieves and displays all password entries from the database.
void update (Scanner scanner)
Updates an existing password entry in the database with new username and password.
void delete (Scanner scanner)
Deletes a password entry from the database based on the service name.
List< Password > readAll ()
Reads all password entries from the database.
void writeAll (List< Password > list)
Writes a list of password entries to the database.
Protected Member Functions
String getDatabaseUrl ()
Retrieves the database URL for the SQLite connection.
Detailed Description
SQLite-based implementation of password storage.
This class uses an SQLite database to store, retrieve, update, and delete password entries. All sensitive data is encrypted before storing in the database.
Definition at line 12 of file DatabasePasswordStorage.java.
Constructor & Destructor Documentation
DatabasePasswordStorage()
com.ucoruh.password.DatabasePasswordStorage.DatabasePasswordStorage (String masterPassword)
Constructs a DatabasePasswordStorage object and initializes the database.
Parameters
masterPassword The master password for encryption/decryption.
Definition at line 30 of file DatabasePasswordStorage.java.
                                                          {
        this.masterPassword = masterPassword;
        createTableIfNotExists();
    }
Member Function Documentation
add()
void com.ucoruh.password.DatabasePasswordStorage.add (Scanner scanner)
Adds a new password entry to the database using user input.
This method reads service, username, and password from the provided Scanner, encrypts the sensitive data, and inserts the new entry into the passwords table.
Parameters
scanner the Scanner object used to obtain user input.
Implements com.ucoruh.password.InterfacePasswordStorage.
Definition at line 75 of file DatabasePasswordStorage.java.
                                     {
        System.out.print("Service: ");
        String service = scanner.nextLine();
        System.out.print("Username: ");
        String user = scanner.nextLine();
        System.out.print("Password: ");
        String pass = scanner.nextLine();
        try {
            // Check if service already exists
            try (Connection conn = DriverManager.getConnection(getDatabaseUrl());
                 PreparedStatement pstmt = conn.prepareStatement(
                        "SELECT 1 FROM passwords WHERE service = ?")) {
                pstmt.setString(1, service);
                try (ResultSet rs = pstmt.executeQuery()) {
                    if (rs.next()) {
                        System.out.println("A password for this service already exists. Use update option to modify it.");
                        return;
                    }
                }
            }
            
            // Encrypt username and password
            String encryptedUser = EncryptionUtil.encrypt(user, masterPassword);
            String encryptedPass = EncryptionUtil.encrypt(pass, masterPassword);
            
            // Insert new record
            try (Connection conn = DriverManager.getConnection(getDatabaseUrl());
                 PreparedStatement pstmt = conn.prepareStatement(
                        "INSERT INTO passwords(service, username, password) VALUES(?, ?, ?)")) {
                pstmt.setString(1, service);
                pstmt.setString(2, encryptedUser);
                pstmt.setString(3, encryptedPass);
                pstmt.executeUpdate();
                System.out.println("Password saved successfully.");
            }
        } catch (SQLException e) {
            System.out.println("Database error: " + e.getMessage());
        } catch (Exception e) {
            System.out.println("Encryption error: " + e.getMessage());
        }
    }
References com.ucoruh.password.EncryptionUtil.encrypt(), and com.ucoruh.password.DatabasePasswordStorage.getDatabaseUrl().
delete()
void com.ucoruh.password.DatabasePasswordStorage.delete (Scanner scanner)
Deletes a password entry from the database based on the service name.
This method prompts the user for the service of the entry to delete and removes the corresponding record from the database.
Parameters
scanner the Scanner object used to obtain user input.
Implements com.ucoruh.password.InterfacePasswordStorage.
Definition at line 240 of file DatabasePasswordStorage.java.
                                        {
        System.out.print("Service to delete: ");
        String service = scanner.nextLine();
        try (Connection conn = DriverManager.getConnection(getDatabaseUrl());
             PreparedStatement pstmt = conn.prepareStatement("DELETE FROM passwords WHERE service = ?")) {
            pstmt.setString(1, service);
            int affected = pstmt.executeUpdate();
            if (affected > 0) {
                System.out.println("Password deleted successfully.");
            } else {
                System.out.println("Service not found.");
            }
        } catch (SQLException e) {
            System.out.println("Database error: " + e.getMessage());
        }
    }
References com.ucoruh.password.DatabasePasswordStorage.getDatabaseUrl().
getDatabaseUrl()
String com.ucoruh.password.DatabasePasswordStorage.getDatabaseUrl () [protected]
Retrieves the database URL for the SQLite connection.
Returns
A string containing the SQLite database URL.
Definition at line 40 of file DatabasePasswordStorage.java.
                                      {
        return DB_URL;
    }
Referenced by com.ucoruh.password.DatabasePasswordStorage.add(), com.ucoruh.password.DatabasePasswordStorage.delete(), com.ucoruh.password.DatabasePasswordStorage.readAll(), com.ucoruh.password.DatabasePasswordStorage.update(), com.ucoruh.password.DatabasePasswordStorage.view(), and com.ucoruh.password.DatabasePasswordStorage.writeAll().
readAll()
List< Password > com.ucoruh.password.DatabasePasswordStorage.readAll ()
Reads all password entries from the database.
This method retrieves all records from the passwords table, decrypts the sensitive data, converts each record into a Password object, and returns a list of these objects.
Returns
A List of Password objects representing all stored password entries.
Implements com.ucoruh.password.InterfacePasswordStorage.
Definition at line 267 of file DatabasePasswordStorage.java.
                                    {
        List<Password> list = new ArrayList<>();
        try (Connection conn = DriverManager.getConnection(getDatabaseUrl());
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery("SELECT * FROM passwords")) {
            while (rs.next()) {
                try {
                    String service = rs.getString("service");
                    String encryptedUsername = rs.getString("username");
                    String encryptedPassword = rs.getString("password");
                    
                    // Decrypt username and password
                    String username = EncryptionUtil.decrypt(encryptedUsername, masterPassword);
                    String password = EncryptionUtil.decrypt(encryptedPassword, masterPassword);
                    
                    list.add(new Password(service, username, password));
                } catch (Exception e) {
                    System.out.println("Error decrypting entry: " + e.getMessage());
                }
            }
        } catch (SQLException e) {
            System.out.println("Database error: " + e.getMessage());
        }
        return list;
    }
References com.ucoruh.password.EncryptionUtil.decrypt(), and com.ucoruh.password.DatabasePasswordStorage.getDatabaseUrl().
update()
void com.ucoruh.password.DatabasePasswordStorage.update (Scanner scanner)
Updates an existing password entry in the database with new username and password.
This method prompts the user for the service to update, along with the new username and password, encrypts the sensitive data, and then updates the corresponding record in the database.
Parameters
scanner the Scanner object used to obtain user input.
Implements com.ucoruh.password.InterfacePasswordStorage.
Definition at line 166 of file DatabasePasswordStorage.java.
                                        {
        System.out.print("Service to update: ");
        String service = scanner.nextLine();
        
        try {
            // Check if service exists and get current values
            String currentUsername = null;
            try (Connection conn = DriverManager.getConnection(getDatabaseUrl());
                 PreparedStatement pstmt = conn.prepareStatement(
                        "SELECT username FROM passwords WHERE service = ?")) {
                pstmt.setString(1, service);
                try (ResultSet rs = pstmt.executeQuery()) {
                    if (rs.next()) {
                        String encryptedUsername = rs.getString("username");
                        currentUsername = EncryptionUtil.decrypt(encryptedUsername, masterPassword);
                    } else {
                        System.out.println("Service not found.");
                        return;
                    }
                }
            }
            
            System.out.print("New username (leave blank to keep current '" + currentUsername + "'): ");
            String username = scanner.nextLine();
            if (username.trim().isEmpty()) {
                username = currentUsername;
            }
            
            System.out.print("New password (leave blank to keep current): ");
            String password = scanner.nextLine();
            
            // Encrypt the new values
            String encryptedUsername = EncryptionUtil.encrypt(username, masterPassword);
            
            if (password.trim().isEmpty()) {
                // Only update username
                try (Connection conn = DriverManager.getConnection(getDatabaseUrl());
                     PreparedStatement pstmt = conn.prepareStatement(
                        "UPDATE passwords SET username = ? WHERE service = ?")) {
                    pstmt.setString(1, encryptedUsername);
                    pstmt.setString(2, service);
                    pstmt.executeUpdate();
                }
            } else {
                // Update both username and password
                String encryptedPassword = EncryptionUtil.encrypt(password, masterPassword);
                try (Connection conn = DriverManager.getConnection(getDatabaseUrl());
                     PreparedStatement pstmt = conn.prepareStatement(
                        "UPDATE passwords SET username = ?, password = ? WHERE service = ?")) {
                    pstmt.setString(1, encryptedUsername);
                    pstmt.setString(2, encryptedPassword);
                    pstmt.setString(3, service);
                    pstmt.executeUpdate();
                }
            }
            
            System.out.println("Password updated successfully.");
            
        } catch (SQLException e) {
            System.out.println("Database error: " + e.getMessage());
        } catch (Exception e) {
            System.out.println("Encryption error: " + e.getMessage());
        }
    }
References com.ucoruh.password.EncryptionUtil.decrypt(), com.ucoruh.password.EncryptionUtil.encrypt(), and com.ucoruh.password.DatabasePasswordStorage.getDatabaseUrl().
view()
void com.ucoruh.password.DatabasePasswordStorage.view ()
Retrieves and displays all password entries from the database.
This method executes an SQL query to obtain all records from the passwords table, decrypts the sensitive data, and prints each entry using the Password class's toString() method.
Implements com.ucoruh.password.InterfacePasswordStorage.
Definition at line 125 of file DatabasePasswordStorage.java.
                       {
        try (Connection conn = DriverManager.getConnection(getDatabaseUrl());
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery("SELECT * FROM passwords")) {
            int count = 0;
            while (rs.next()) {
                try {
                    String service = rs.getString("service");
                    String encryptedUsername = rs.getString("username");
                    String encryptedPassword = rs.getString("password");
                    
                    // Decrypt username and password
                    String username = EncryptionUtil.decrypt(encryptedUsername, masterPassword);
                    String password = EncryptionUtil.decrypt(encryptedPassword, masterPassword);
                    
                    count++;
                    System.out.println(count + ". " + new Password(service, username, password));
                } catch (Exception e) {
                    System.out.println("Error decrypting entry: " + e.getMessage());
                }
            }
            
            if (count == 0) {
                System.out.println("No records found.");
            }
        } catch (SQLException e) {
            System.out.println("Database error: " + e.getMessage());
        }
    }
References com.ucoruh.password.EncryptionUtil.decrypt(), and com.ucoruh.password.DatabasePasswordStorage.getDatabaseUrl().
writeAll()
void com.ucoruh.password.DatabasePasswordStorage.writeAll (List< Password > list)
Writes a list of password entries to the database.
This method clears the existing contents of the passwords table and inserts all password entries from the provided list, encrypting sensitive data before storage.
Parameters
list A List of Password objects to be written to the database.
Implements com.ucoruh.password.InterfacePasswordStorage.
Definition at line 304 of file DatabasePasswordStorage.java.
                                              {
        try (Connection conn = DriverManager.getConnection(getDatabaseUrl());
             Statement stmt = conn.createStatement()) {
            stmt.execute("DELETE FROM passwords"); // clear all
            
            for (Password p : list) {
                try {
                    // Encrypt username and password
                    String encryptedUsername = EncryptionUtil.encrypt(p.getUsername(), masterPassword);
                    String encryptedPassword = EncryptionUtil.encrypt(p.getPassword(), masterPassword);
                    
                    try (PreparedStatement pstmt = conn.prepareStatement(
                            "INSERT INTO passwords(service, username, password) VALUES (?, ?, ?)")) {
                        pstmt.setString(1, p.getService());
                        pstmt.setString(2, encryptedUsername);
                        pstmt.setString(3, encryptedPassword);
                        pstmt.executeUpdate();
                    }
                } catch (Exception e) {
                    System.out.println("Error encrypting data for " + p.getService() + ": " + e.getMessage());
                }
            }
        } catch (SQLException e) {
            System.out.println("Database error: " + e.getMessage());
        }
    }
References com.ucoruh.password.EncryptionUtil.encrypt(), and com.ucoruh.password.DatabasePasswordStorage.getDatabaseUrl().
The documentation for this class was generated from the following file:
password-app/src/main/java/com/ucoruh/password/DatabasePasswordStorage.java