com.ucoruh.password.AuthManager Class Reference
Singleton class that manages user authentication.
Public Member Functions
boolean isMasterPasswordSet ()
void createMasterPassword (Scanner scanner)
boolean login (Scanner scanner)
String getMasterPassword ()
boolean changeMasterPassword (Scanner scanner)
void userMenu (Scanner scanner)
Static Public Member Functions
static AuthManager getInstance ()
static void resetInstance ()
Detailed Description
Singleton class that manages user authentication.
This class handles the creation and verification of the master password. It also provides a stub for user-specific functionality.
Definition at line 17 of file AuthManager.java.
Member Function Documentation
changeMasterPassword()
boolean com.ucoruh.password.AuthManager.changeMasterPassword (Scanner scanner)
Change the master password.
Parameters
scanner The Scanner object for user input.
Returns
true if password change is successful.
Definition at line 142 of file AuthManager.java.
                                                         {
        System.out.print("Enter current master password: ");
        String currentPassword = scanner.nextLine();
        String hashedCurrent = EncryptionUtil.hashString(currentPassword);
        
        // Verify the current password before allowing a change
        if (!masterPassword.equals(hashedCurrent) && !masterPassword.equals(currentPassword)) {
            System.out.println("Incorrect current password.");
            return false;
        }
        
        System.out.print("Enter new master password: ");
        String newPassword = scanner.nextLine();
        System.out.print("Confirm new master password: ");
        String confirmPassword = scanner.nextLine();
        
        if (!newPassword.equals(confirmPassword)) {
            System.out.println("Passwords do not match.");
            return false;
        }
        
        masterPassword = EncryptionUtil.hashString(newPassword);
        saveMasterPassword();
        System.out.println("Master password changed successfully.");
        return true;
    }
References com.ucoruh.password.EncryptionUtil.hashString().
Referenced by com.ucoruh.password.AuthManager.userMenu().
createMasterPassword()
void com.ucoruh.password.AuthManager.createMasterPassword (Scanner scanner)
Create the master password.
Parameters
scanner The Scanner object for user input.
Definition at line 104 of file AuthManager.java.
                                                      {
        String input = scanner.nextLine();
        masterPassword = EncryptionUtil.hashString(input);
        saveMasterPassword();
        System.out.println("Master password set successfully.");
    }
References com.ucoruh.password.EncryptionUtil.hashString().
Referenced by com.ucoruh.password.PasswordApp.runApp().
getInstance()
static AuthManager com.ucoruh.password.AuthManager.getInstance () [static]
Retrieve the singleton instance.
Returns
AuthManager instance.
Definition at line 50 of file AuthManager.java.
                                            {
        if (instance == null) {
            instance = new AuthManager();
        }
        return instance;
    }
Referenced by com.ucoruh.password.gui.AddPasswordController.AddPasswordController(), com.ucoruh.password.gui.DeletePasswordController.DeletePasswordController(), com.ucoruh.password.gui.GeneratePasswordController.GeneratePasswordController(), com.ucoruh.password.gui.PasswordManagerGUI.PasswordManagerGUI(), com.ucoruh.password.PasswordApp.runApp(), com.ucoruh.password.gui.UpdatePasswordController.UpdatePasswordController(), and com.ucoruh.password.gui.ViewPasswordController.ViewPasswordController().
getMasterPassword()
String com.ucoruh.password.AuthManager.getMasterPassword ()
Getter for the master password.
Returns
The master password.
Definition at line 133 of file AuthManager.java.
                                      {
        return masterPassword;
    }
Referenced by com.ucoruh.password.PasswordApp.runApp().
isMasterPasswordSet()
boolean com.ucoruh.password.AuthManager.isMasterPasswordSet ()
Check if the master password is set.
Returns
true if master password is set; otherwise false.
Definition at line 96 of file AuthManager.java.
                                         {
        return masterPassword != null && !masterPassword.isEmpty();
    }
Referenced by com.ucoruh.password.PasswordApp.runApp().
login()
boolean com.ucoruh.password.AuthManager.login (Scanner scanner)
Perform user login.
Parameters
scanner The Scanner object for user input.
Returns
true if login is successful.
Definition at line 116 of file AuthManager.java.
                                          {
        String input = scanner.nextLine();
        String hashedInput = EncryptionUtil.hashString(input);
        boolean success = masterPassword.equals(hashedInput);
        
        if (success) {
            // Store the plaintext password for encryption/decryption operations
            masterPassword = input;
        }
        
        return success;
    }
References com.ucoruh.password.EncryptionUtil.hashString().
Referenced by com.ucoruh.password.PasswordApp.runApp().
resetInstance()
static void com.ucoruh.password.AuthManager.resetInstance () [static]
Resets the singleton instance.
This method is intended for testing purposes only.
Definition at line 63 of file AuthManager.java.
                                       {
        instance = null;
    }
userMenu()
void com.ucoruh.password.AuthManager.userMenu (Scanner scanner)
Display user-specific menu for authentication operations.
Parameters
scanner The Scanner object for user input.
Definition at line 173 of file AuthManager.java.
                                          {
        boolean back = false;
        while (!back) {
            System.out.println("\n==== USER AUTHENTICATION MENU ====");
            System.out.println("1. Change Master Password");
            System.out.println("2. Test Authentication");
            System.out.println("0. Back to Main Menu");
            System.out.print("Your choice: ");
            
            String input = scanner.nextLine();
            try {
                int choice = Integer.parseInt(input);
                switch (choice) {
                    case 1:
                        changeMasterPassword(scanner);
                        break;
                    case 2:
                        System.out.print("Enter master password to verify: ");
                        String testPassword = scanner.nextLine();
                        String hashedTest = EncryptionUtil.hashString(testPassword);
                        if (masterPassword.equals(hashedTest) || masterPassword.equals(testPassword)) {
                            System.out.println("Authentication successful.");
                        } else {
                            System.out.println("Authentication failed.");
                        }
                        break;
                    case 0:
                        back = true;
                        break;
                    default:
                        System.out.println("Invalid choice.");
                        break;
                }
            } catch (NumberFormatException e) {
                System.out.println("Invalid number.");
            }
        }
    }
References com.ucoruh.password.AuthManager.changeMasterPassword(), and com.ucoruh.password.EncryptionUtil.hashString().
Referenced by com.ucoruh.password.PasswordApp.runApp().
The documentation for this class was generated from the following file:
password-app/src/main/java/com/ucoruh/password/AuthManager.java